student: False
model_training: "rl"
model_path: "/share/portal/nlc62/CritiQ_ReTRy/example_models/teacher_nav.zip"
env_id: "StretchNav"
device: "cuda:0"
run_name: "nav_teacher"
record_video: True
frame_skip: 40
max_episode_steps: 400
num_ep: 20
reset_bank_path: ""
seed: 2