student: False
model_training: "rl"
model_path: "/share/portal/nlc62/CritiQ_ReTRy/example_models/teacher_push.zip"
env_id: "singlepush"
device: "cuda:0"
run_name: "push_teacher"
record_video: True
frame_skip: 20
max_episode_steps: 100
num_ep: 20
reset_bank_path: ""
seed: 1