student: True
model_training: "rl"
model_path: "/share/portal/nlc62/CritiQ_ReTRy/example_models/rl_friction_recover.zip"
env_id: "StretchDrawer"
device: "cuda:0"
run_name: "drawer_retry"
record_video: True
frame_skip: 20
max_episode_steps: 150
num_ep: 10
reset_bank_path: ""
seed: 1